export const ROLE_TAXONOMY = {
  "Technology & Software": [
    "Software Engineer",
    "Frontend Engineer",
    "Backend Engineer",
    "Full-stack Engineer",
    "Mobile App Developer",
    "iOS Developer",
    "Android Developer",
    "QA Engineer",
    "Software Test Engineer",
    "DevOps Engineer",
    "Site Reliability Engineer",
    "Platform Engineer",
    "Cloud Engineer",
    "Solutions Architect",
    "Systems Engineer",
    "Security Engineer",
    "Cybersecurity Analyst",
    "Network Engineer",
    "Database Administrator",
    "Technical Support Engineer",
    "IT Analyst",
    "IT Support Specialist",
    "Product Manager",
    "Technical Program Manager",
    "Scrum Master",
  ],
  "AI, Data & Analytics": [
    "AI Engineer",
    "Generative AI Engineer",
    "GenAI Engineer",
    "LLM Engineer",
    "RAG Engineer",
    "AI Agent Engineer",
    "Prompt Engineer",
    "Applied AI Engineer",
    "AI Solutions Engineer",
    "Conversational AI Engineer",
    "Machine Learning Engineer",
    "MLOps Engineer",
    "LLMOps Engineer",
    "Data Scientist",
    "Data Analyst",
    "Business Intelligence Analyst",
    "Analytics Engineer",
    "Data Engineer",
    "Data Platform Engineer",
    "NLP Engineer",
    "Computer Vision Engineer",
    "Research Scientist",
    "AI Research Assistant",
    "Quantitative Researcher",
  ],
  "Business, Management & Operations": [
    "Business Analyst",
    "Operations Analyst",
    "Strategy Analyst",
    "Management Consultant",
    "Associate Consultant",
    "Product Manager",
    "Project Manager",
    "Project Coordinator",
    "Program Coordinator",
    "Operations Manager",
    "Business Development Representative",
    "Sales Development Representative",
    "Account Executive",
    "Customer Success Associate",
    "Customer Success Manager",
    "Revenue Operations Analyst",
    "Growth Analyst",
    "Market Research Analyst",
    "Executive Assistant",
    "Administrative Coordinator",
  ],
  "Finance, Accounting & Economics": [
    "Financial Analyst",
    "FP&A Analyst",
    "Investment Analyst",
    "Equity Research Analyst",
    "Risk Analyst",
    "Credit Analyst",
    "Quantitative Analyst",
    "Treasury Analyst",
    "Corporate Finance Analyst",
    "Accounting Associate",
    "Audit Associate",
    "Tax Associate",
    "Compliance Analyst",
    "Actuarial Analyst",
    "Economics Research Assistant",
    "Portfolio Analyst",
    "Banking Analyst",
    "Insurance Analyst",
  ],
  "Healthcare, Life Sciences & Public Health": [
    "Clinical Research Assistant",
    "Clinical Research Coordinator",
    "Clinical Data Coordinator",
    "Lab Technician",
    "Research Assistant",
    "Bioinformatics Analyst",
    "Public Health Analyst",
    "Healthcare Analyst",
    "Medical Assistant",
    "Regulatory Affairs Associate",
    "Medical Device Associate",
    "Pharmaceutical Associate",
    "Quality Assurance Associate",
    "Biomedical Engineer",
    "Health Informatics Analyst",
    "Epidemiology Assistant",
  ],
  "Engineering, Manufacturing & Construction": [
    "Mechanical Engineer",
    "Manufacturing Engineer",
    "Product Design Engineer",
    "CAD Engineer",
    "SolidWorks Designer",
    "AutoCAD Technician",
    "Aerospace Engineer",
    "Battery Engineer",
    "EV Systems Engineer",
    "Validation Engineer",
    "Quality Engineer",
    "Process Engineer",
    "Maintenance Engineer",
    "Industrial Engineer",
    "Electrical Engineer",
    "Embedded Systems Engineer",
    "Controls Engineer",
    "Hardware Engineer",
    "Power Systems Engineer",
    "Electronics Engineer",
    "Civil Engineer",
    "Structural Engineer",
    "Construction Project Engineer",
    "Transportation Engineer",
    "Environmental Engineer",
    "Site Engineer",
    "Robotics Engineer",
    "Automation Engineer",
  ],
  "Design, Architecture & Creative": [
    "UX Designer",
    "UI Designer",
    "Product Designer",
    "Graphic Designer",
    "Motion Designer",
    "Service Designer",
    "Design Strategist",
    "UX Researcher",
    "UX Research Assistant",
    "Interaction Designer",
    "Brand Designer",
    "Content Designer",
    "Architecture Intern",
    "Junior Architect",
    "Interior Designer",
    "Urban Planner",
    "3D Artist",
    "Video Editor",
    "Photographer",
    "Animator",
  ],
  "Marketing, Communications & Media": [
    "Marketing Associate",
    "Digital Marketing Specialist",
    "Content Strategist",
    "Content Writer",
    "Copywriter",
    "Social Media Coordinator",
    "SEO Specialist",
    "Brand Associate",
    "Public Relations Associate",
    "Communications Associate",
    "Journalist",
    "Video Producer",
    "Media Coordinator",
    "Community Manager",
    "Event Coordinator",
    "Email Marketing Specialist",
    "Growth Marketing Associate",
  ],
  "Education, Research & Academia": [
    "Teaching Assistant",
    "Tutor",
    "Curriculum Developer",
    "Instructional Designer",
    "Education Coordinator",
    "Academic Advisor",
    "Research Assistant",
    "Graduate Research Assistant",
    "Lab Assistant",
    "Program Assistant",
    "Student Success Coordinator",
    "Admissions Assistant",
    "Learning Experience Designer",
  ],
  "Law, Policy, Government & Compliance": [
    "Policy Analyst",
    "Legal Assistant",
    "Paralegal",
    "Compliance Analyst",
    "Privacy Analyst",
    "Regulatory Affairs Associate",
    "Government Affairs Intern",
    "ESG Analyst",
    "Public Policy Associate",
    "Legislative Assistant",
    "Risk & Compliance Associate",
    "Immigration Assistant",
    "Contract Analyst",
  ],
  "Psychology, Social Sciences & Human Services": [
    "Research Assistant",
    "Behavioral Health Technician",
    "HR Associate",
    "People Operations Associate",
    "Case Manager",
    "Program Coordinator",
    "Social Services Assistant",
    "Community Outreach Coordinator",
    "Survey Research Analyst",
    "User Research Assistant",
    "Mental Health Program Assistant",
  ],
  "Environmental, Sustainability & Energy": [
    "Environmental Analyst",
    "Sustainability Analyst",
    "Climate Analyst",
    "Energy Analyst",
    "Renewable Energy Associate",
    "ESG Analyst",
    "Environmental Engineer",
    "Conservation Assistant",
    "Sustainability Coordinator",
    "Carbon Accounting Analyst",
  ],
  "Supply Chain, Logistics & Retail": [
    "Supply Chain Analyst",
    "Logistics Coordinator",
    "Procurement Analyst",
    "Inventory Analyst",
    "Demand Planner",
    "Operations Analyst",
    "Warehouse Operations Coordinator",
    "Retail Analyst",
    "Merchandising Associate",
    "Vendor Management Associate",
    "Transportation Analyst",
  ],
  "Hospitality, Tourism & Service": [
    "Hospitality Management Trainee",
    "Hotel Operations Associate",
    "Event Coordinator",
    "Travel Coordinator",
    "Guest Services Associate",
    "Restaurant Operations Associate",
    "Tourism Marketing Associate",
  ],
  "Entrepreneurship & Startups": [
    "Founder",
    "Co-founder",
    "Startup Analyst",
    "Venture Analyst",
    "Product Operations Associate",
    "Growth Associate",
    "Community Lead",
    "Startup Intern",
    "Innovation Associate",
  ],
} as const;

export const INDUSTRY_OPTIONS = [
  "Technology",
  "Software",
  "Artificial Intelligence",
  "Generative AI",
  "AI Agents",
  "Enterprise AI",
  "AI Infrastructure",
  "Data & Analytics",
  "Cybersecurity",
  "Cloud Computing",
  "FinTech",
  "Banking",
  "Finance",
  "Accounting",
  "Insurance",
  "Consulting",
  "Healthcare",
  "Biotechnology",
  "Pharmaceuticals",
  "Medical Devices",
  "Public Health",
  "Education",
  "Higher Education",
  "EdTech",
  "Manufacturing",
  "Automotive",
  "Aerospace",
  "Robotics",
  "Construction",
  "Architecture",
  "Real Estate",
  "Energy",
  "Renewable Energy",
  "Climate / Sustainability",
  "Government",
  "Public Policy",
  "Legal Services",
  "Nonprofit",
  "Retail",
  "E-commerce",
  "Supply Chain / Logistics",
  "Telecommunications",
  "Media",
  "Entertainment",
  "Journalism",
  "Sports",
  "Hospitality",
  "Travel / Tourism",
  "Agriculture",
  "Food & Beverage",
  "Fashion",
  "Consumer Goods",
  "Other",
];

const MAJOR_ROLE_SUGGESTIONS: Record<string, string[]> = {
  "Computer Science": [
    "Software Engineer",
    "Backend Engineer",
    "Data Engineer",
    "Cybersecurity Analyst",
    "Cloud Engineer",
    "Platform Engineer",
    "Product Manager",
    "Generative AI Engineer",
    "LLM Engineer",
  ],
  "Artificial Intelligence": [
    "AI Engineer",
    "Machine Learning Engineer",
    "Generative AI Engineer",
    "LLM Engineer",
    "RAG Engineer",
    "Data Scientist",
    "MLOps Engineer",
    "NLP Engineer",
    "Computer Vision Engineer",
  ],
  "Data Science": [
    "AI Engineer",
    "Machine Learning Engineer",
    "Generative AI Engineer",
    "LLM Engineer",
    "RAG Engineer",
    "Data Scientist",
    "MLOps Engineer",
    "NLP Engineer",
    "Computer Vision Engineer",
  ],
  Finance: [
    "Financial Analyst",
    "FP&A Analyst",
    "Investment Analyst",
    "Risk Analyst",
    "Quantitative Analyst",
    "Treasury Analyst",
    "Compliance Analyst",
  ],
  Accounting: [
    "Accounting Associate",
    "Audit Associate",
    "Tax Associate",
    "Financial Analyst",
    "Risk Analyst",
    "Compliance Analyst",
  ],
  "Business Administration": [
    "Business Analyst",
    "Product Manager",
    "Operations Analyst",
    "Strategy Analyst",
    "Management Consultant",
    "Customer Success Associate",
    "Revenue Operations Analyst",
  ],
  Healthcare: [
    "Clinical Research Assistant",
    "Lab Technician",
    "Bioinformatics Analyst",
    "Public Health Analyst",
    "Clinical Data Coordinator",
  ],
  Biology: [
    "Clinical Research Assistant",
    "Lab Technician",
    "Bioinformatics Analyst",
    "Public Health Analyst",
    "Clinical Data Coordinator",
  ],
  "Mechanical Engineering": [
    "Mechanical Engineer",
    "Manufacturing Engineer",
    "Product Design Engineer",
    "CAD Engineer",
    "Aerospace Engineer",
    "Battery Engineer",
    "EV Systems Engineer",
    "Validation Engineer",
  ],
  "Electrical Engineering": [
    "Electrical Engineer",
    "Embedded Systems Engineer",
    "Controls Engineer",
    "Hardware Engineer",
    "Power Systems Engineer",
    "Electronics Engineer",
    "Validation Engineer",
  ],
  "Civil Engineering": [
    "Civil Engineer",
    "Structural Engineer",
    "Construction Project Engineer",
    "Transportation Engineer",
    "Environmental Engineer",
    "Site Engineer",
  ],
  Design: [
    "UX Designer",
    "Product Designer",
    "Graphic Designer",
    "Service Designer",
    "Design Strategist",
    "UX Researcher",
  ],
  Architecture: [
    "Architecture Intern",
    "Junior Architect",
    "Interior Designer",
    "Urban Planner",
    "Service Designer",
  ],
  Psychology: [
    "Research Assistant",
    "UX Research Assistant",
    "HR Associate",
    "Behavioral Health Technician",
    "Case Manager",
  ],
};

const MAJOR_INDUSTRY_SUGGESTIONS: Record<string, string[]> = {
  "Computer Science": ["Technology", "Software", "Artificial Intelligence", "Cybersecurity", "Cloud Computing"],
  "Artificial Intelligence": ["Artificial Intelligence", "Generative AI", "AI Agents", "Enterprise AI", "AI Infrastructure"],
  "Data Science": ["Data & Analytics", "Artificial Intelligence", "Finance", "Healthcare", "Consulting"],
  Finance: ["Finance", "Banking", "FinTech", "Insurance", "Consulting"],
  "Business Administration": ["Consulting", "Technology", "Finance", "Healthcare", "Retail"],
  Healthcare: ["Healthcare", "Public Health", "Medical Devices", "Pharmaceuticals", "Biotechnology"],
  Biology: ["Biotechnology", "Healthcare", "Pharmaceuticals", "Public Health", "Medical Devices"],
  "Mechanical Engineering": ["Manufacturing", "Automotive", "Aerospace", "Robotics", "Energy"],
  Design: ["Technology", "Software", "Media", "Entertainment", "Consumer Goods"],
  Architecture: ["Architecture", "Construction", "Real Estate", "Climate / Sustainability"],
};

const DEFAULT_ROLES = [
  "Business Analyst",
  "Project Coordinator",
  "Research Assistant",
  "Operations Analyst",
  "Associate Consultant",
  "Program Coordinator",
  "Customer Success Associate",
  "Market Research Analyst",
];

const DEFAULT_INDUSTRIES = ["Technology", "Finance", "Healthcare", "Consulting", "Education", "Manufacturing"];

export const ALL_ROLE_OPTIONS = Array.from(new Set(Object.values(ROLE_TAXONOMY).flat()));

export function getSuggestedRolesForMajor(major: string) {
  return MAJOR_ROLE_SUGGESTIONS[major] ?? DEFAULT_ROLES;
}

export function getSuggestedIndustriesForMajor(major: string) {
  return MAJOR_INDUSTRY_SUGGESTIONS[major] ?? DEFAULT_INDUSTRIES;
}

export function searchRoles(query: string, major: string) {
  return searchOptions(query, query.trim() ? ALL_ROLE_OPTIONS : getSuggestedRolesForMajor(major));
}

export function searchIndustries(query: string, major: string) {
  return searchOptions(query, query.trim() ? INDUSTRY_OPTIONS : getSuggestedIndustriesForMajor(major));
}

function searchOptions(query: string, options: string[]) {
  const term = query.trim().toLowerCase();
  const matches = term ? options.filter((option) => option.toLowerCase().includes(term)) : options;
  return matches.slice(0, term ? 20 : 12);
}
