from fastapi import APIRouter

from app.api.v1.endpoints import (
    ai_domain_review,
    admin_quality_review,
    admin_notifications,
    debug,
    evidence_access_links,
    extension_proof,
    extension_proof_github_analysis,
    extension_proof_workflow_analysis,
    github_portfolio,
    github_proofs,
    github_recruiter_proof_reports,
    github_semantic_verification_results,
    health,
    live_website_check,
    notifications,
    permissions,
    project_defense_analysis,
    proof_versioning,
    admin_user_roles,
    recruiter_candidate_comparisons,
    public_work_passport,
    recruiter_candidates,
    skill_evidence,
    skill_evidence_timeline,
    skill_evidence_profile,
    student,
    verification_readiness,
    website_evidence_discovery,
    workflow_visible_evidence,
    workflow_visual_frames,
    verification_review,
    website_analyzer,
    website_browser_verification_runs,
    website_proof_sessions,
    website_semantic_verification_results,
    website_verification_runs,
    work_passport_status,
    work_passport_analytics,
    workflow_privacy_scan,
)

api_router = APIRouter()

api_router.include_router(health.router, tags=["health"])
api_router.include_router(
    student.router,
    prefix="/student",
    tags=["student"],
)
api_router.include_router(
    notifications.router,
    prefix="/student/notifications",
    tags=["student-notifications"],
)
api_router.include_router(
    permissions.router,
    prefix="/me",
    tags=["current-user-permissions"],
)
api_router.include_router(
    work_passport_analytics.router,
    prefix="/student/work-passport",
    tags=["work-passport-analytics"],
)
api_router.include_router(
    skill_evidence.router,
    prefix="/student/skill-evidence",
    tags=["skill-evidence"],
)
api_router.include_router(
    skill_evidence_profile.router,
    prefix="/student/skill-evidence-profiles",
    tags=["skill-evidence-profiles"],
)
api_router.include_router(
    website_verification_runs.router,
    prefix="/student/skill-evidence",
    tags=["website-verification-runs"],
)
api_router.include_router(
    website_browser_verification_runs.router,
    prefix="/student/skill-evidence",
    tags=["website-browser-verification-runs"],
)
api_router.include_router(
    github_semantic_verification_results.router,
    prefix="/student/skill-evidence",
    tags=["github-semantic-verification-results"],
)
api_router.include_router(
    evidence_access_links.router,
    prefix="/student/skill-evidence",
    tags=["evidence-access-links"],
)
api_router.include_router(
    github_recruiter_proof_reports.router,
    prefix="/student/skill-evidence",
    tags=["github-recruiter-proof-reports"],
)
api_router.include_router(
    website_semantic_verification_results.router,
    prefix="/student/skill-evidence",
    tags=["website-semantic-verification-results"],
)
api_router.include_router(
    website_analyzer.router,
    prefix="/student/website-analysis",
    tags=["website-analysis"],
)
api_router.include_router(
    website_evidence_discovery.router,
    prefix="/student/website-analysis",
    tags=["website-evidence-discovery"],
)
api_router.include_router(
    github_portfolio.router,
    prefix="/student/github-portfolio",
    tags=["github-portfolio"],
)
api_router.include_router(
    github_proofs.router,
    prefix="/student/github-proofs",
    tags=["github-proofs"],
)
api_router.include_router(
    recruiter_candidates.router,
    prefix="/recruiter/candidates",
    tags=["recruiter-candidates"],
)
api_router.include_router(
    extension_proof.router,
    prefix="/student/extension-proof/sessions",
    tags=["extension-proof-sessions"],
)
api_router.include_router(
    proof_versioning.router,
    prefix="/student/extension-proof/sessions",
    tags=["proof-evidence-versioning"],
)
api_router.include_router(
    extension_proof_github_analysis.router,
    prefix="/student/extension-proof/sessions",
    tags=["extension-proof-github-analysis"],
)
api_router.include_router(
    extension_proof_workflow_analysis.router,
    prefix="/student/extension-proof/sessions",
    tags=["extension-proof-workflow-analysis"],
)
api_router.include_router(
    workflow_visible_evidence.router,
    prefix="/student/extension-proof/sessions",
    tags=["workflow-visible-evidence"],
)
api_router.include_router(
    workflow_visual_frames.router,
    prefix="/student/extension-proof/sessions",
    tags=["workflow-visual-frames"],
)
api_router.include_router(
    live_website_check.router,
    prefix="/student/extension-proof/sessions",
    tags=["live-website-check"],
)
api_router.include_router(
    workflow_privacy_scan.router,
    prefix="/student/extension-proof/sessions",
    tags=["workflow-privacy-scan"],
)
api_router.include_router(
    project_defense_analysis.router,
    prefix="/student/extension-proof/sessions",
    tags=["project-defense-analysis"],
)
api_router.include_router(
    verification_readiness.router,
    prefix="/student/extension-proof/sessions",
    tags=["verification-readiness"],
)
api_router.include_router(
    verification_review.router,
    prefix="/student/extension-proof/sessions",
    tags=["verification-review"],
)
api_router.include_router(
    ai_domain_review.router,
    prefix="/student/extension-proof/sessions",
    tags=["ai-domain-review"],
)
api_router.include_router(
    work_passport_status.router,
    prefix="/student/extension-proof/sessions",
    tags=["work-passport-status"],
)
api_router.include_router(
    skill_evidence_timeline.router,
    prefix="/student/extension-proof/sessions",
    tags=["skill-evidence-timeline"],
)
api_router.include_router(
    public_work_passport.student_router,
    prefix="/student/extension-proof/sessions",
    tags=["public-work-passport"],
)
api_router.include_router(
    public_work_passport.access_router,
    prefix="/student",
    tags=["public-work-passport-access"],
)
api_router.include_router(
    public_work_passport.public_router,
    prefix="/public",
    tags=["public-work-passport"],
)
api_router.include_router(
    recruiter_candidate_comparisons.router,
    prefix="/public/recruiter",
    tags=["recruiter-candidate-comparisons"],
)
api_router.include_router(
    public_work_passport.admin_router,
    prefix="/admin",
    tags=["recruiter-requester-admin"],
)
api_router.include_router(
    admin_quality_review.router,
    prefix="/admin/quality-review",
    tags=["admin-quality-review"],
)
api_router.include_router(
    admin_notifications.router,
    prefix="/admin/notifications",
    tags=["admin-notifications"],
)
api_router.include_router(
    admin_user_roles.router,
    prefix="/admin/users",
    tags=["admin-user-roles"],
)
api_router.include_router(
    verification_review.admin_router,
    prefix="/admin/verification-reviews",
    tags=["verification-review-admin"],
)
api_router.include_router(
    website_proof_sessions.router,
    prefix="/student/website-proof/sessions",
    tags=["website-proof-sessions"],
)
api_router.include_router(
    debug.router,
    prefix="/debug",
    tags=["debug"],
)
