from fastapi import APIRouter

from app.api.v1.endpoints import (
    debug,
    evidence_access_links,
    extension_proof,
    extension_proof_github_analysis,
    extension_proof_workflow_analysis,
    github_portfolio,
    github_recruiter_proof_reports,
    github_semantic_verification_results,
    health,
    live_website_check,
    recruiter_candidates,
    skill_evidence,
    skill_evidence_profile,
    student,
    website_analyzer,
    website_browser_verification_runs,
    website_proof_sessions,
    website_semantic_verification_results,
    website_verification_runs,
    workflow_privacy_scan,
)

api_router = APIRouter()

api_router.include_router(health.router, tags=["health"])
api_router.include_router(
    student.router,
    prefix="/student",
    tags=["student"],
)
api_router.include_router(
    skill_evidence.router,
    prefix="/student/skill-evidence",
    tags=["skill-evidence"],
)
api_router.include_router(
    skill_evidence_profile.router,
    prefix="/student/skill-evidence-profiles",
    tags=["skill-evidence-profiles"],
)
api_router.include_router(
    website_verification_runs.router,
    prefix="/student/skill-evidence",
    tags=["website-verification-runs"],
)
api_router.include_router(
    website_browser_verification_runs.router,
    prefix="/student/skill-evidence",
    tags=["website-browser-verification-runs"],
)
api_router.include_router(
    github_semantic_verification_results.router,
    prefix="/student/skill-evidence",
    tags=["github-semantic-verification-results"],
)
api_router.include_router(
    evidence_access_links.router,
    prefix="/student/skill-evidence",
    tags=["evidence-access-links"],
)
api_router.include_router(
    github_recruiter_proof_reports.router,
    prefix="/student/skill-evidence",
    tags=["github-recruiter-proof-reports"],
)
api_router.include_router(
    website_semantic_verification_results.router,
    prefix="/student/skill-evidence",
    tags=["website-semantic-verification-results"],
)
api_router.include_router(
    website_analyzer.router,
    prefix="/student/website-analysis",
    tags=["website-analysis"],
)
api_router.include_router(
    github_portfolio.router,
    prefix="/student/github-portfolio",
    tags=["github-portfolio"],
)
api_router.include_router(
    recruiter_candidates.router,
    prefix="/recruiter/candidates",
    tags=["recruiter-candidates"],
)
api_router.include_router(
    extension_proof.router,
    prefix="/student/extension-proof/sessions",
    tags=["extension-proof-sessions"],
)
api_router.include_router(
    extension_proof_github_analysis.router,
    prefix="/student/extension-proof/sessions",
    tags=["extension-proof-github-analysis"],
)
api_router.include_router(
    extension_proof_workflow_analysis.router,
    prefix="/student/extension-proof/sessions",
    tags=["extension-proof-workflow-analysis"],
)
api_router.include_router(
    live_website_check.router,
    prefix="/student/extension-proof/sessions",
    tags=["live-website-check"],
)
api_router.include_router(
    workflow_privacy_scan.router,
    prefix="/student/extension-proof/sessions",
    tags=["workflow-privacy-scan"],
)
api_router.include_router(
    website_proof_sessions.router,
    prefix="/student/website-proof/sessions",
    tags=["website-proof-sessions"],
)
api_router.include_router(
    debug.router,
    prefix="/debug",
    tags=["debug"],
)
