-- VeriBridge AI — Migration 039: Fix workflow_visual_frame_evidence schema
--
-- Two bugs introduced after migration 035 was deployed:
--
--  1. frame_type check constraint is missing values that the backend now inserts:
--       • video_upload_marker  — stored when a video is uploaded but cv2/ffmpeg
--                                are unavailable, so the UI shows "Video uploaded"
--                                instead of "No video recorded".
--       • video_keyframe       — stored by VideoKeyframeExtractorService for each
--                                frame extracted from the uploaded video.
--
--  2. confidence_score column is missing but written by analyze_visual_frame()
--     every time OCR/vision analysis runs (VisualFrameObservation.confidence_score).
--
-- All changes are idempotent / non-destructive — no data is dropped.
-- ---------------------------------------------------------------------------

-- ---------------------------------------------------------------------------
-- 1. Drop old frame_type check constraint and replace with the full list
--    Default constraint name generated by PostgreSQL for an inline CHECK is
--    <table>_<column>_check.
-- ---------------------------------------------------------------------------

alter table public.workflow_visual_frame_evidence
  drop constraint if exists workflow_visual_frame_evidence_frame_type_check;

alter table public.workflow_visual_frame_evidence
  add constraint workflow_visual_frame_evidence_frame_type_check
    check (frame_type in (
      -- Original values (migration 035)
      'recording_start',
      'page_load',
      'after_click',
      'after_upload',
      'after_form_submit',
      'after_dom_mutation',
      'after_result_detected',
      'recording_end',
      'screenshot',
      -- Video pipeline values (added in migration 039)
      'video_upload_marker',
      'video_keyframe'
    ));

-- ---------------------------------------------------------------------------
-- 2. Add confidence_score column (written by analyze_visual_frame on update)
--    Type: double precision, nullable (not every frame is analysed), default 0.
-- ---------------------------------------------------------------------------

alter table public.workflow_visual_frame_evidence
  add column if not exists confidence_score double precision not null default 0.0;

-- ---------------------------------------------------------------------------
-- Index on confidence_score for future quality filtering queries
-- ---------------------------------------------------------------------------

create index if not exists workflow_visual_frame_evidence_confidence_idx
  on public.workflow_visual_frame_evidence (proof_session_id, confidence_score);
